### PR TITLE
Update kustomization-quickstart.yml

### PR DESCRIPTION
**Pull request by dwilliams-armory**
Removing the expose from the default/quickstart kustomize as this has caused problems with customer installs in the past.

### CODE REVIEW

**Comment by german-muzquiz** [comment]
What kind of problems does this have? 

Instead of making users figure out how to expose spinnaker, I'd like to fix operator, the configs, or the comments in the configs if there's a problem. The goal of the quickstart recipe is precisely to have a working spinnaker installation (not for production use) out of the box without any extra configuration, and by removing the expose function, users will just not be able to login to spinnaker without doing port forwards, which is certianly much more trouble than commenting the expose config if they don't want to use it.

**Comment by dwilliams-armory** [comment]
The expose functionality only work for very specific configurations.  Most of our customers don't fall into those very specific configurations.  The expose example used in the quickstart relies on AWS EKS with public endpoint for the EKS control plane (or networking setup to connect to the public AWS API) and using the AWS ALB for load balancing.  Very few, if any, of our customers fit into this specific configuration.  If we or the customer forgets to turn off expose before the initial push of the SpinnakerService CRD, it causes a fair amount of debugging and unraveling.  This is an attempt to prevent those debugging sessions from happening.

**Comment by german-muzquiz** [comment]
So there are 2 different things:
1. Reliance on public resources. As far as I know service load balancers are not related to the kubernetes control plane, since they are created on the worker nodes, only the subnets of the worker nodes affect these load balancers. It's true though that by default they try to create public ELBs instead of private ones. However there's already an example config specifically for creating internal AWS ELBs with SSL [here](https://github.com/armory/spinnaker-kustomize-patches/blob/master/expose/patch-lb-aws.yml). This cannot be used as a default though, because it only works in AWS.
2. Removing expose config after it was used initially: We'd need to know what's the problem it causes and try to fix it before removing a feature.

It seems that you try to use the quickstart recipe for internal/private EKS clusters. Since there are other installations that don't use EKS or where it is public (which is the [default EKS behavior](https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html)), it would be better to use something like the eks-prod recipe or create another recipe for air gapped environments instead.

**Comment by dwilliams-armory** [comment]
I'm not trying to remove the expose functionality with this, I'm just trying to default it to off.  We haven't been able to use the expose functionality with any of our customers due to the specifics of each of our customer environments.  None of them use a standard, public EKS cluster.  I would like to be able to pass this repo to a customer and have them start and add what they need.  It makes this much more complicated when we have to explain to the customer "use this repo, but remember to disable this thing and change the version of that thing..." to get them started.  Adding items to a minimum base is far easier than trying to remove things that are already configured incorrectly.

**Comment by devorbitus** [comment]
If I am on GKE I need to disable `patch-lb` as well, I would also need to do it if I was using minnaker

**Comment by german-muzquiz** [comment]
I like the idea of having a minimum, mostly empty base for adding things rather than trying to change the quickstart recipe into a generic, catch-all solution. Recipes are opinionated installations and the quickstart also adds docker and kubernetes accounts, which you also need to remove if you don't deploy to kubernetes.

**Comment by devorbitus** [comment]
ok, so if we create a quickstart-like file that will actually work in most places what would you like it to be called?

**Comment by german-muzquiz** [comment]
Something like `kustomization-min.yml` or `kustomization-minimum.yml`? I think it would only have a persistent storage configuration.

Also if you found bugs in expose-lb let's create tickets/issues for tackling them, like the one mentioned about removing expose causing issues.

**Comment by dwilliams-armory** [comment]
I'm fine changing the name, but I'll then be setting the newly named file as the default.  No matter the name, the point of this PR to to make the default of this repo support the largest number of environments out of the box.

**Comment by dwilliams-armory** [comment]
Reverted the changes to the quickstart file, copied the quickstart to a minimum file, made the changes, and updated the symlink to point to the minimum.

**Review by german-muzquiz — APPROVED** [review]

**Pull request merged**
